naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

complexity:
  LongParameterList:
    ignoreAnnotated: ['Composable']

style:
  MagicNumber:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
